services:
  server:
    restart: always
    container_name: adr-server
    image: node:lts-alpine
    env_file:
      - ./client/.env
    volumes:
      - ./server:/app
    ports:
      - "4000:4000"
    working_dir: /app
    command: /bin/sh -c "apk add curl && npm install && node server.js"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:4000"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  client:
    restart: always
    container_name: adr-client
    image: node:lts-alpine
    volumes:
      - ./client:/app
    ports:
      - "80:3000"
    env_file:
      - ./client/.env
    entrypoint: /bin/sh -c "until wget -q --spider http://server:4000; do echo 'Waiting for server...'; sleep 5; done; npm install && npm run build && npm run start"
    working_dir: /app

networks:
  mynetwork:
    driver: bridge
    external: true
