version: "3.8"
services:
  Server:
    image: node:12.21-alpine3.10
    container_name: vercin-adr-server
    working_dir: /home/node/app
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
    networks:
      - adr
    volumes:
      - ./src:/home/node/app
    command: "node ./server/server.js"

  Client:
    image: node:12.21-alpine3.10
    container_name: vercin-adr-client
    working_dir: /home/node/app
    restart: always
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: adr.7cav.us
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: adr.7cav.us
    ports:
      - 8080:3000
    networks:
      - adr
      - edge
    volumes:
      - ./src/client:/home/node/app
    command: "npm start"
networks:
  edge:
  adr: