# This is a basic workflow to help you get started with Actions

name: BETA_LINT_FORMAT_CHECK

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - Development

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # deployment
  lint_format_check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Prettiier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--check {**/*,*}.{js,jsx,json,html,css,yml,yaml}"
          prettier_version: "2.8.8"
