name: Development Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        type: string
        default: "development"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Client Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: |
            7cav/apps_beta_client:${{ github.sha }}
            7cav/apps_beta_client:latest

      - name: Build and Push Server Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: |
            7cav/apps_beta_server:${{ github.sha }}
            7cav/apps_beta_server:latest

      - name: Force Watchtower Update
        run: |
          curl -H "Authorization: Bearer ${{ secrets.WATCHER_KEY }}" https://watcher.7cav.us/v1/update