# This is a basic workflow to help you get started with Actions

name: ADR_PUSH

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # deployment
  deployment:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Build ReactApp
        uses: actions/setup-node@v3
      - name: Pull from Repo
        run: git -C /opt/compose/docker-adr/src pull && cd /opt/compose/docker-adr/src
      - name: Build to Prod
        run: npm run build --if-present
      - name: run tests
        run: npm test
      - name: change directory
        run: cd /opt/compose/docker-adr
      - name: restart container
        run: docker-compose restart
