name: PROD_URL_CHECK

on:
    pull_request:
      branches: [ main ]
      paths:
        - 'client/src/App.js'

jobs:
    check-url:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check API URL
        run: |
          if ! grep -E '^[^/]*https://bff.adr.7cav.us/roster/combat' client/src/App.js; then
            echo "ERROR: Production API URL is either absent or commented out."
            exit 1
          else
            echo "Production API URL is present and not commented out."
          fi