name: Production Deploy

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Client Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/client.Dockerfile
          push: true
          tags: |
            7cav/apps_client:${{ github.ref_name }}
            7cav/apps_client:latest

      - name: Build and Push Server Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/server.Dockerfile
          push: true
          tags: |
            7cav/apps_server:${{ github.ref_name }}
            7cav/apps_server:latest

      - name: Force Watchtower Update
        run: |
          curl -H "Authorization: Bearer ${{ secrets.WATCHER_KEY }}" https://watcher.7cav.us/v1/update